### ISSUE TITLE
Schema discussion 

### ISSUE THREAD

**Issue by shpiyu** [upaytech/as-server#1]

**Comment by shpiyu** [comment]
[schema-diagram.pdf](https://github.com/upaytech/as-server/files/2908987/apnasaamaan.pdf) Review the schema and share your views. 
@Pac23 @alivenotions @AnkushMalik @OmkarPathak

**Comment by shpiyu** [comment]
link to db diagram, https://dbdiagram.io/d/5c76398df7c5bb70c72f236d
let's make changes here. easy to export postgresql queries

**Comment by mm-git01** [comment]
> link to db diagram, https://dbdiagram.io/d/5c76398df7c5bb70c72f236d
> let's make changes here. easy to export postgresql queries

maybe we could use elasticsearch

**Comment by shpiyu** [comment]
Please support your suggestions with some points on why we should go with a particular technology and how useful is it for our use case. Along with the benefits the technology brings, also consider the cost involved and its ease of use. 

Discussing the use cases of the application will help us to easily choose a technology. Let's do that today

**Comment by shpiyu** [comment]
closing this issue as all of us agreed on using postgres
