### ISSUE TITLE
The password to connect to the DB should not be committed to version control

### ISSUE THREAD

**Issue by alivenotions** [upaytech/as-server#14]
**Description**
Currently, the password is stored in the `src/config/knexfile.js` file. This shouldn't be the case.
Store the credentials in the `.env` file.

**Comment by vaibhav-sharma-frontend** [comment]
@alivenotions I would like to work on this issue.

**Comment by alivenotions** [comment]
Sure!

**Comment by vaibhav-sharma-frontend** [comment]
@alivenotions can u elaborate more what I need to do in this bcz I never use docker.
