### ISSUE TITLE
Choice of License

### ISSUE THREAD

**Issue by alivenotions** [upaytech/as-server#4]
I have two licenses that I feel we can contemplate:
1. MIT
2. GNU GPL

Which should we choose?
Any other appropriate license can also be suggested

**Comment by mm-git01** [comment]
MIT 
https://choosealicense.com/licenses/

**Comment by alivenotions** [comment]
GNU GPL allows that if anyone builds anything on this code and tries to sell that product, then that product also *has to be* GNU GPL licensed.
MIT permits everything in a way.

**Comment by OmkarPathak** [comment]
I think for some organisation like UPAY should be having GNU GLP V3 license
https://www.gnu.org/licenses/gpl-3.0.en.html

**Comment by alivenotions** [comment]
Going ahead with GNU GPL v3.
